package com.vemcomigo.radio;

import android.app.*;import android.os.*;import android.graphics.Color;import android.view.*;import android.widget.*;import org.json.*;import java.io.*;import java.net.*;import java.util.*;import java.util.regex.*;

public class BibleActivity extends Activity {
    Spinner book; NumberPicker chapter; TextView ref,text; Button prev,next; int currentBook=0,currentChapter=1,page=0; ArrayList<String> verses=new ArrayList<>(); ArrayList<Integer> nums=new ArrayList<>();
    final String[] names={"Gênesis","Êxodo","Levítico","Números","Deuteronômio","Josué","Juízes","Rute","1 Samuel","2 Samuel","1 Reis","2 Reis","1 Crônicas","2 Crônicas","Esdras","Neemias","Ester","Jó","Salmos","Provérbios","Eclesiastes","Cânticos","Isaías","Jeremias","Lamentações","Ezequiel","Daniel","Oséias","Joel","Amós","Obadias","Jonas","Miquéias","Naum","Habacuque","Sofonias","Ageu","Zacarias","Malaquias","Mateus","Marcos","Lucas","João","Atos","Romanos","1 Coríntios","2 Coríntios","Gálatas","Efésios","Filipenses","Colossenses","1 Tessalonicenses","2 Tessalonicenses","1 Timóteo","2 Timóteo","Tito","Filemom","Hebreus","Tiago","1 Pedro","2 Pedro","1 João","2 João","3 João","Judas","Apocalipse"};
    final String[] slugs={"genesis","exodus","leviticus","numbers","deuteronomy","joshua","judges","ruth","1-samuel","2-samuel","1-kings","2-kings","1-chronicles","2-chronicles","ezra","nehemiah","esther","job","psalms","proverbs","ecclesiastes","song-of-solomon","isaiah","jeremiah","lamentations","ezekiel","daniel","hosea","joel","amos","obadiah","jonah","micah","nahum","habakkuk","zephaniah","haggai","zechariah","malachi","matthew","mark","luke","john","acts","romans","1-corinthians","2-corinthians","galatians","ephesians","philippians","colossians","1-thessalonians","2-thessalonians","1-timothy","2-timothy","titus","philemon","hebrews","james","1-peter","2-peter","1-john","2-john","3-john","jude","revelation"};
    final int[] chapters={50,40,27,36,34,24,21,4,31,24,22,25,29,36,10,13,10,42,150,31,12,8,66,52,5,48,12,14,3,9,1,4,7,3,3,3,2,14,4,28,16,24,21,28,16,16,13,6,6,4,4,5,3,6,4,3,1,13,5,5,3,5,1,1,1,1,22};
    @Override protected void onCreate(Bundle b){super.onCreate(b);setContentView(R.layout.activity_bible);book=findViewById(R.id.book);chapter=findViewById(R.id.chapter);ref=findViewById(R.id.reference);text=findViewById(R.id.text);prev=findViewById(R.id.prev);next=findViewById(R.id.next); ArrayAdapter<String> a=new ArrayAdapter<String>(this,android.R.layout.simple_spinner_item,names){public View getView(int p,View v,android.view.ViewGroup g){TextView t=(TextView)super.getView(p,v,g);t.setTextColor(Color.WHITE);return t;}};a.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);book.setAdapter(a);book.setSelection(42);book.setOnItemSelectedListener(new android.widget.AdapterView.OnItemSelectedListener(){public void onNothingSelected(android.widget.AdapterView<?> x){}public void onItemSelected(android.widget.AdapterView<?> x,View v,int p,long id){currentBook=p;chapter.setMinValue(1);chapter.setMaxValue(chapters[p]);chapter.setValue(1);load();}});chapter.setOnValueChangedListener((p,o,n)->{page=0;load();});prev.setOnClickListener(v->{if(page>0){page--;render();}else if(chapter.getValue()>1){chapter.setValue(chapter.getValue()-1);}});next.setOnClickListener(v->{if((page+1)*10<verses.size()){page++;render();}else if(chapter.getValue()<chapters[currentBook]){chapter.setValue(chapter.getValue()+1);}});}
    void load(){text.setText("Carregando…");ref.setText(names[currentBook]+" "+chapter.getValue()); new Thread(()->{try{URL u=new URL("https://free.bible/bible/pt/"+slugs[currentBook]+"/"+chapter.getValue()+".json");HttpURLConnection c=(HttpURLConnection)u.openConnection();c.setConnectTimeout(12000);c.setReadTimeout(20000);c.setRequestMethod("GET");c.setRequestProperty("User-Agent","WebRadioVemComigoNoGloria/1.0");int code=c.getResponseCode();if(code!=200)throw new IOException("HTTP "+code);BufferedReader r=new BufferedReader(new InputStreamReader(c.getInputStream(),"UTF-8"));StringBuilder s=new StringBuilder();String line;while((line=r.readLine())!=null)s.append(line);JSONArray arr=new JSONObject(s.toString()).getJSONArray("verses");ArrayList<String> vv=new ArrayList<>();ArrayList<Integer> nn=new ArrayList<>();for(int i=0;i<arr.length();i++){JSONObject o=arr.getJSONObject(i);nn.add(o.getInt("v"));vv.add(o.getString("t"));}runOnUiThread(()->{verses=vv;nums=nn;page=0;render();});}catch(Exception e){runOnUiThread(()->{ref.setText(names[currentBook]+" "+chapter.getValue());text.setText("Não foi possível carregar este capítulo agora. Verifique a internet e tente novamente.");});}}).start();}
    void render(){int from=page*10,to=Math.min(from+10,verses.size());StringBuilder s=new StringBuilder();for(int i=from;i<to;i++)s.append(nums.get(i)).append("  ").append(verses.get(i)).append("\n\n");text.setText(s.toString());ref.setText(names[currentBook]+" "+chapter.getValue()+"  •  pág. "+(page+1));}
}
