package com.vemcomigo.radio;

import android.app.*;import android.os.*;import android.content.*;import android.graphics.Color;import android.net.Uri;import android.view.*;import android.widget.*;import java.text.SimpleDateFormat;import java.util.*;

public class MainActivity extends Activity {
    TextView clock,status,now; Button play,bible,devotional,word,share,down,up; Switch hourSwitch; Handler h=new Handler(Looper.getMainLooper()); boolean playing=false;
    final Runnable clockRun=new Runnable(){ public void run(){ clock.setText(new SimpleDateFormat("HH:mm",Locale.getDefault()).format(new Date())); h.postDelayed(this,1000); }};
    @Override protected void onCreate(Bundle b){super.onCreate(b); setContentView(R.layout.activity_main); bind(); startService(new Intent(this,RadioService.class)); clockRun.run();
        play.setOnClickListener(v->{ if(playing) cmd(RadioService.ACTION_STOP); else cmd(RadioService.ACTION_PLAY); playing=!playing; play.setText(playing?"■":"▶"); status.setText(playing?"● AO VIVO":"● DESLIGADA"); });
        down.setOnClickListener(v->volume(-1)); up.setOnClickListener(v->volume(1));
        hourSwitch.setOnCheckedChangeListener((b1,c)->{ Intent i=new Intent(this,RadioService.class); i.setAction(RadioService.ACTION_HOUR); i.putExtra("enabled",c); startService(i); });
        bible.setOnClickListener(v->showBible()); devotional.setOnClickListener(v->showDevotional()); word.setOnClickListener(v->showWord()); share.setOnClickListener(v->share()); }
    void bind(){ clock=findViewById(R.id.clock); status=findViewById(R.id.status); now=findViewById(R.id.nowPlaying); play=findViewById(R.id.play); bible=findViewById(R.id.bible); devotional=findViewById(R.id.devotional); word=findViewById(R.id.word); share=findViewById(R.id.share); down=findViewById(R.id.volumeDown); up=findViewById(R.id.volumeUp); hourSwitch=findViewById(R.id.hourSwitch); }
    void cmd(String a){ Intent i=new Intent(this,RadioService.class);i.setAction(a);startService(i); }
    void volume(int d){ android.media.AudioManager am=(android.media.AudioManager)getSystemService(AUDIO_SERVICE); am.adjustStreamVolume(android.media.AudioManager.STREAM_MUSIC,d>0?android.media.AudioManager.ADJUST_RAISE:android.media.AudioManager.ADJUST_LOWER,android.media.AudioManager.FLAG_SHOW_UI); }
    void share(){Intent s=new Intent(Intent.ACTION_SEND);s.setType("text/plain");s.putExtra(Intent.EXTRA_TEXT,"Ouça a Web Rádio Vem Comigo no Glória ao vivo: https://webradiovemcomigonogloria.ismyradio.com");startActivity(Intent.createChooser(s,"Compartilhar rádio"));}
    void dialog(String title,String body){ final Dialog d=new Dialog(this); LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setPadding(24,22,24,18);l.setBackgroundColor(Color.rgb(11,18,32)); TextView t=new TextView(this);t.setText(title);t.setTextColor(Color.rgb(255,209,42));t.setTextSize(22);t.setTypeface(null,1);l.addView(t); TextView x=new TextView(this);x.setText(body);x.setTextColor(Color.WHITE);x.setTextSize(17);x.setPadding(0,18,0,18);l.addView(x); LinearLayout nav=new LinearLayout(this);nav.setGravity(Gravity.CENTER);Button prev=new Button(this);prev.setText("‹");Button close=new Button(this);close.setText("FECHAR");Button next=new Button(this);next.setText("›");nav.addView(prev);nav.addView(close);nav.addView(next);l.addView(nav);close.setOnClickListener(v->d.dismiss()); d.setContentView(l);Window w=d.getWindow();if(w!=null)w.setBackgroundDrawableResource(android.R.color.transparent);d.show(); }
    void showWord(){String[] a={"Confie no Senhor de todo o seu coração. — Provérbios 3:5","O Senhor é a minha força e o meu escudo. — Salmos 28:7","Tudo posso naquele que me fortalece. — Filipenses 4:13","Alegrai-vos sempre no Senhor. — Filipenses 4:4","O amor de Deus lança fora o medo. — 1 João 4:18","Entrega o teu caminho ao Senhor. — Salmos 37:5","O Senhor está perto dos que têm o coração quebrantado. — Salmos 34:18"};int day=Calendar.getInstance().get(Calendar.DAY_OF_YEAR);dialog("Palavra do Dia",a[day%a.length]);}
    void showDevotional(){String[] a={"Hoje, faça uma pausa e agradeça a Deus pelo que Ele já fez. Entregue a Ele também aquilo que ainda preocupa o seu coração.","Mesmo quando você não enxerga o próximo passo, Deus continua presente. Ore, confie e caminhe com fé.","Não deixe o medo decidir por você. Busque a Deus, fortaleça o coração e prossiga com esperança."};int day=Calendar.getInstance().get(Calendar.DAY_OF_YEAR);dialog("Devocional",a[day%a.length]);}
    void showBible(){dialog("Bíblia Sagrada","A Bíblia será aberta por capítulos. Nesta versão Lite, o leitor usa conteúdo bíblico de domínio público carregado por capítulo, sem colocar um site dentro do aplicativo.\n\nPrimeiro capítulo: João 3.");}
    @Override protected void onDestroy(){h.removeCallbacks(clockRun);super.onDestroy();}
}
